#!/bin/bash

echo Generating swapfile...

fallocate -l 512m /var/swapfile
chmod 600 /var/swapfile
mkswap /var/swapfile
systemctl enable --now var-swapfile.swap

systemctl disable swapfile.service
rm /etc/systemd/system/swapfile.service $0
