#!/bin/bash
set -e
trap 'exec /bin/sh' ERR
export PATH

cat << 'EOF'

+----------------------------+
| Debian for WM8505 Netbooks |
|      First Boot Setup      |
+----------------------------+

EOF

# Set hostname
read -rp "Enter a hostname: " hostname
echo "$hostname" > /etc/hostname
cat > /etc/hosts << EOF
127.0.0.1	localhost
127.0.1.1	$hostname

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

# Create user account
read -rp "Username for your account: " username
adduser --gecos "" "$username"
adduser "$username" sudo

# Configure timezone
dpkg-reconfigure tzdata

# Generate SSH keys
dpkg-reconfigure dropbear

# Setup swap file
fallocate -l 256M /var/swapfile
chmod 600 /var/swapfile
mkswap /var/swapfile
systemctl enable var-swapfile.swap

# Setup WLAN
update-alternatives --set regulatory.db /lib/firmware/regulatory.db-upstream
systemctl enable wlan-gpio.service

# Set rootfs to expand
systemctl enable expand-rootfs.service

mv /sbin/init.orig /sbin/init
exec /sbin/init
